version: '2'
services:
  nginx:
    build: ./docker/images/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/hosts:/etc/nginx/conf.d
      - ./:/var/www/textile-yii
      - ./docker/logs:/var/log/nginx
    depends_on:
      - php
  php:
    build: ./docker/images/php
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/textile-yii
      - ./docker/php/php.ini-development:/usr/local/etc/php/php.ini
    environment:
      XDEBUG_CONFIG: remote_host=127.0.0.1

#  postgres:
#    image: postgres:latest
#    build: docker/images/postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - docker/posgres:/var/lib/posgresql/data
#    environment:
#      POSTGRES_DB: dev8
#      POSTGRES_USER: dev8
#      POSTGRES_PASSWORD: dev8
#      PGDATA: /var/lib/postgresql/data
#      DB_HOST: postgres
#
#  mysql:
#    image: mariadb:latest
#    ports:
#      - "3306:3306"
#    volumes:
#      - docker/mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: dev8